### ISSUE TITLE
hanbkim - 2주차 목표

### ISSUE THREAD

**Issue by kimchijinju** [42StudyGame/RandomDiceDefense42-Server#1]
- [x] 기술스택 확정하기
asp.net로 확정했습니다! 버전은 정하지 않았습니다.
- [x] 정한 기술스택 튜토리얼 해보기
-> 어디까지 할 수 있는지 공유

**Comment by jongfeel** [comment]
discord에는 공유가 되었지만
확정된 기술스택 내용을 적어주세요
