### ISSUE TITLE
협업 : 공동 프로젝트 DB connectionString 해결

### ISSUE THREAD

**Issue by gyujun9403** [42StudyGame/RandomDiceDefense42-Server#16]

**Comment by kimchijinju** [comment]
환경변수에 db connection에 필요한 정보를 담아 불러오는 방식을 채택했습니다.
터미널에서 환경변수를 설정하고 불러오니 불러와지지 않는 이슈가 있었는데, visual studto 프로젝트 환경변수에 담아 해결했습니다.
