### ISSUE TITLE
데이터 모델링 보완 혹은 전환(SQL안쓰는 쪽으로)

### ISSUE THREAD

**Issue by gyujun9403** [42StudyGame/RandomDiceDefense42-Server#19]

**Comment by gyujun9403** [comment]
찾아본 결과 Dapper의 SQL사용시, 파라메터방식을 사용하면 SQL인젝션 공격도 방지할 수 있어서, 당장은 EF방식으로 시간을 들여서 전환 할 필요가 없어보인다([링크](https://www.learndapper.com/parameters)). 
특히 EF를 적용해보려고 하는 중 에러가 발생하기도 하고, .Net6버전에 대한 정보도 부족하여 사용이 직관적인 Dapper를 사용하고 일단은 C++을 이용한 서버 부분에 시간을 더 안배하고자 한다.

**Comment by jacking75** [comment]
EF는 성능 이슈가 있습니다. 그리고 코드로 DB를 조작하는 것이라서 DBA분들이 별로 좋아하지 않고요,
EF가 이전보다 성능이 좋아졌다고 하지만 여전히 Dapper 등에 비해서 느리고, 최적화 등을 하기 어려워서 선호하지 않습니다.

**Comment by gyujun9403** [comment]
@jacking75 오 감사합니다! 말씀해주신 키워드 위주로 찾아서 정리해보겠습니다...!
