### ISSUE TITLE
3주차 목표

### ISSUE THREAD

**Issue by kimchijinju** [42StudyGame/RandomDiceDefense42-Server#4]
- [x] 웹 프로젝트에 DB 붙이기
- [ ] 로그인 기능 최대한 구현해보기. (쿠키, 세션 등 필요한 부분이 무엇이 있는지 공부, 진행되는대로 이슈에 올리겠습니다.)

**Comment by jongfeel** [comment]
하루나 이틀 단위의 작업 분량으로 잘 나누셔서 issue 만들고 진행하시면 좋을 것 같습니다.
할 일 한 줄 적어놓고 코드를 엄청 만드는 신입 개발자가 되지 않기 위한 훈련을 미리 한다 생각해 주세요.

**Comment by jongfeel** [comment]
좋습니다.

어려우시겠지만 서버는 데이터 설계가 핵심입니다.

그래서 아래와 같은 내용을 정리하면서 버전 업데이트를 하면 좋습니다.

- API에 대한 상세 내용: 요청 데이터 구조, 응답 데이터 구조, 에러 코드 정의 및 의미
- DB에 대한 상세 내용: Collection, Document key, value 정의

**Comment by jacking75** [comment]
가능하면 DB는 MySQL을 사용하세요
MongoDB를 사용해야할 이유가 없다면 보편적으로 많이 사용하는 기술을 사용하는 것이 더 좋습니다.
특히 이 프로젝트가 포트폴리오로 제출할 것이라면 더 그렇고

**Comment by jongfeel** [comment]
좋은 의견 감사합니다.

**Comment by kimchijinju** [comment]
DB 연동은 성공했고, 로그인 기능은 좀 더 공부해보며 월요일에 진행상황 공유하겠습니다.
https://github.com/42StudyGame/RandomDiceDefense42-Server/issues/6#issue-1402051206

**Comment by giftof** [comment]
DB연동할때 겪은 시행착오도 기록 남겨놓으시면 좋습니다 :)

**Comment by kimchijinju** [comment]
Db를 효율적으로 다루기 위해 dapper를 사용하기로 했습니다. 
로그인 기능 구현은, 이번주에는 더 진행을 할 수 없을 것 같아 이슈 닫겠습니다.
